9

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,27 +29,27 @@ jobs:
           mask-password: 'true'
 
       # Step 3: Build Docker Images for Testing
-      - name: Build Docker Images for Testing
-        run: |
-          docker compose build
+     # - name: Build Docker Images for Testing
+      #  run: |
+       #   docker compose build
 
       # Step 4: Run Tests on Local Containers
-      - name: Start Local Containers for Testing
-        run: |
-          docker compose up -d
-          sleep 10  # Wait for services to initialize
+     # - name: Start Local Containers for Testing
+      #  run: |
+       #   docker compose up -d
+        #  sleep 10  # Wait for services to initialize
 
-      - name: Test Application Locally
-        run: |
-          echo "Testing frontend..."
-          curl -f http://localhost:3001 || exit 1
+      #- name: Test Application Locally
+       # run: |
+        #  echo "Testing frontend..."
+         # curl -f http://localhost:3001 || exit 1
 
-          echo "Testing backend..."
-          curl -f http://localhost:3000 || exit 1
+        #  echo "Testing backend..."
+         # curl -f http://localhost:3000 || exit 1
 
-      - name: Stop and Clean Up Local Containers
-        run: |
-          docker compose down
+   #   - name: Stop and Clean Up Local Containers
+    #    run: |
+     #    docker compose down
 
       # Step 5: Tag and Push Docker Images to ECR
       - name: Build and Push Docker Images
